images:
  -
    image: 
      - ghcr.io/daniel-memo-ict/shopware-docker/5/nginx
    buildTags: [ 'dev' ]
    dockerFile: nginx/Dockerfile
    context: nginx
    variables:
      APP_DOCUMENT_ROOT: '/var/www/html'
    templates:
      nginx/Dockerfile.twig: nginx/Dockerfile
      nginx/10-classic.conf: nginx/rootfs/etc/nginx/sites-enabled/www.conf
    tags:
      php80:
        phpVersion: '8.0'
        phpVersionNumeric: 80
      php81:
        phpVersion: '8.1'
        phpVersionNumeric: 81
  -
    image: 
      - ghcr.io/daniel-memo-ict/shopware-docker/6/nginx
    buildTags: [ 'dev' ]
    dockerFile: nginx/Dockerfile
    context: nginx
    variables:
      APP_DOCUMENT_ROOT: '/var/www/html/public'
    templates:
      nginx/Dockerfile.twig: nginx/Dockerfile
      nginx/10-platform.conf: nginx/rootfs/etc/nginx/sites-enabled/www.conf
    tags:
      php80:
        phpVersion: '8.0'
        phpVersionNumeric: 80
      php81:
        phpVersion: '8.1'
        phpVersionNumeric: 81
      php82:
        phpVersion: '8.2'
        phpVersionNumeric: 82
      php83:
        phpVersion: '8.3'
        phpVersionNumeric: 83
      php84:
        phpVersion: '8.4'
        phpVersionNumeric: 83
