name: Build Docker Images

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  generate-jobs:
    name: Generate Jobs
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[build skip]')"
    outputs:
      strategy: ${{ steps.generate-jobs.outputs.strategy }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - id: generate-jobs
      name: Generate Jobs
      run: |
        npm install
        strategy="$(node build.js generateJobs)"
        echo "::set-output name=strategy::$strategy"

  build-amd64:
    needs: generate-jobs
    strategy: ${{ fromJson(needs.generate-jobs.outputs.strategy).amd64 }}
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ matrix.name }}
        run: ${{ matrix.runs.build }}

  build-arm64:
    needs: generate-jobs
    strategy: ${{ fromJson(needs.generate-jobs.outputs.strategy).arm64 }}
    name: ${{ matrix.name }}
    runs-on: ARM64
    steps:
      - uses: actions/checkout@v3

      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build ${{ matrix.name }}
        run: ${{ matrix.runs.build }}

      - name: Cleanup
        run: docker system prune -a -f

  build-manifest:
    name: Generate Manifest file
    strategy: ${{ fromJson(needs.generate-jobs.outputs.strategy).merge }}
    needs:
      - generate-jobs
      - build-amd64
      - build-arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login into Github Docker Registery
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Merge
        run: ${{ matrix.runs.merge }}
